Repository achrafyahyaoui/hotel, pull requests merged in 2020-05, with the labels that each got.

#2 this is a test
  lara-hotel/app/Http/Controllers/CustomerController.php
Labels: Code Review

#3 delete fonction
  lara-hotel/app/Http/Controllers/CustomerController.php
Labels: Ready for Test

#4 fix delete client
  lara-hotel/app/Http/Controllers/CustomerController.php
  lara-hotel/resources/views/clients/index.blade.php
Labels: Ready to be Merged

#5 WIP: Client Details
  lara-hotel/app/Http/Controllers/CustomerController.php
  lara-hotel/public/images/Profile-icon.png
  lara-hotel/resources/views/clients/detail.blade.php
  lara-hotel/resources/views/clients/index.blade.php
Labels: Code Review

#6 modif1
  lara-hotel/.env.example
  lara-hotel/resources/views/clients/edit.blade.php
Labels: Code Review
